#!/usr/bin/env bash
BACKUP_PATH="/home/$USER/$USER.backup.tar.gz"
TO_BACKUP="/home/$USER"

# tar -zcvpf $BACKUP_PATH /home/$user

# # Compress
# # Zip
# # Files
# # Preserve Permissions
sudo tar cpf - $TO_BACKUP -P | pv -s $(du -sb $TO_BACKUP | awk '{print $1}')  > $BACKUP_PATH
