#!/usr/bin/env bash
#
# Script to fix duplicated columns in CSV and create SQLITE DB
#

FILENAME=$1
TMP_FILENAME=/tmp/csv2sqlite.csv
DB_NAME=csv2sqlite.db

# Cleanup
rm -rf $DB_NAME
rm -rf $TMP_FILENAME

# Update column names
FIXED_COLUMNS=$(head -1 "$FILENAME" | python -c "import sys,uuid; c=sys.stdin.read().strip(); columns = [x.lower() for x in c.split(',')]; new_cols = [(columns.count(x)>1 and x + f'-{uuid.uuid4()}'[:9] or x) for x in columns] ; print(','.join(new_cols))")

# Write columns and data
echo $FIXED_COLUMNS > $TMP_FILENAME
sed -r 1d "$FILENAME" >> $TMP_FILENAME
sqlite3 -csv $DB_NAME ".import '$TMP_FILENAME' data"

# Cleanup is awesome
rm -rf $TMP_FILENAME
