#!/usr/bin/env fish
# sudo bash -c "cat /sys/kernel/debug/dri/0/amdgpu_pm_info"
# watch -n 0.5  

# To check your GPU's P-states, execute:
# PSTATE=$(cat /sys/class/drm/card0/device/pp_od_clk_voltage)

# To check your GPU utilization, execute:
set UTIL (cat /sys/class/drm/card0/device/gpu_busy_percent)

# To check your GPU frequency, execute:
set FREQUENCY (cat /sys/class/drm/card0/device/pp_dpm_sclk)

# To check your GPU temperature, execute:
set TEMP (cat /sys/class/drm/card0/device/hwmon/hwmon*/temp1_input)

# To check your VRAM frequency, execute:
set VRAM_FREQUENCY (cat /sys/class/drm/card0/device/pp_dpm_mclk)

# To check your VRAM usage, execute:
set VRAM_USAGE (cat /sys/class/drm/card0/device/mem_info_vram_used)

# To check your VRAM size, execute:
set VRAM_SIZE (cat /sys/class/drm/card0/device/mem_info_vram_total)


# echo $PSTATE
# echo $UTIL
# echo $FREQUENCY
# echo $TEMP
# echo $VRAM_FREQUENCY  # TODO fix

set percent_usage (math -s2 "$VRAM_USAGE / $VRAM_SIZE * 100")
set temp (math -s0 "$TEMP / 1000")

echo "Util: $UTIL Temp: $temp VRAM Usage: $percent_usage%"
# echo "$VRAM_USAGE / $VRAM_SIZE"
