#!/usr/bin/env bash

# On local runs on port 5435 to avoid conflicts.
# User: postgres
# Password: 1337

docker run \
    -d \
    --name local-psql \
    -e POSTGRES_PASSWORD=1337 \
    -e PGDATA=/var/lib/postgresql/data/pgdata \
    -p 127.0.0.1:5435:5432 \
    --restart unless-stopped \
    --volume=$HOME/.local/share/postgres:/var/lib/postgresql/data \
    postgres

