#!/usr/bin/env bash

mkdir secure_backup

cp -r ~/.ssh secure_backup/.ssh
cp -r ~/.kube secure_backup/.kube
cp -r ~/.credentials secure_backup/.credentials
cp -r ~/.gnupg secure_backup/.gnupg
cp -r ~/.aws secure_backup/.aws
