#!/bin/zsh
# BATTERY_LEVEL=$(acpi -b | awk '{print $4}')
BATTERY_LEVEL=$(acpi -b | cut -d "," -f 2)
DATE_AND_TIME=$(date +'%Y-%m-%d %l:%M:%S %p')
VOLUME=$(pamixer --get-volume)
BRIGHTNESS=$(brightnessctl -m | cut -d "," -f 4)

echo BL: $BRIGHTNESS VOL: $VOLUME BAT: $BATTERY_LEVEL '   ' $DATE_AND_TIME
