#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot"

DOTBOT_SCRIPT_PATH="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive

PACKAGES_CONFIG=packages.yaml
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_SCRIPT_PATH}" -d "${BASEDIR}" -c "${PACKAGES_CONFIG}" --plugin-dir "${BASEDIR}/dotbot_plugin_aptget" "${@}"
