#!/usr/bin/env bash

install_base_debian () {
    sudo apt-get update

    sudo apt-get install -y \
        cargo \
        curl \
        fd-find \
        fish \
        htop \
        httpie \
        iotop \
        neovim \
        net-tools \
        nodejs \
        npm \
        python3 \
        python3-pip \
        rclone \
        tmux \
        universal-ctags \
        wget \
    && echo "apt install success"

    install_base_snap
}

install_base_snap(){
    sudo snap install go --classic
}

install_base_manjaro() {
    sudo pacman -S --quiet --needed --noconfirm \
        base-devel \
        bat \
        bind-tools \
        cmake \
        ctags \
        curl \
        exa \
        fd \
        fish \
        fzf \
        go \
        go \
        helm \
        htop \
        httpie \
        jq \
        k9s \
        kubectl \
        neovim \
        npm \
        postgresql-libs \
        rclone \
        ripgrep \
        rust \
        rust-analyzer \
        sd \
        shellcheck \
        terraform \
        tldr \
        tmux \
        traceroute \
        wget \
        xmlsec \
        yarn \
    && echo -e '\033[1mBase install success\033[0m'
}

install_base_arch () {
    sudo pacman -S --needed --noconfirm \
        autoconf \
        base-devel \
        bind-tools \
        cmake \
        ctags \
        curl \
        fd \
        fish \
        fzf \
        helm \
        htop \
        httpie \
        inotify-tools \
        iotop \
        jq \
        k9s \
        kubectl \
        mysql \
        neovim \
        npm \
        p7zip \
        pkgconf \
        postgresql-libs \
        python-pip \
        python3 \
        reflector \
        rust \
        rust-analyzer \
        shellcheck \
        terraform \
        tmux \
        xmlsec \
    && echo -e '\033[1mBase install success\033[0m'
}


install_go_packages() {
    export GOPATH=~/code/go

    go get -u github.com/motemen/gore/cmd/gore
    go get -u github.com/stamblerre/gocode
    go get -u golang.org/x/tools/cmd/godoc
    go get -u golang.org/x/tools/cmd/goimports
    go get -u golang.org/x/tools/cmd/gorename
    go get -u golang.org/x/tools/cmd/guru
    go get -u github.com/cweill/gotests/...
    go get -u github.com/fatih/gomodifytags
    go get -u github.com/ericchiang/pup
}

install_devspace() {
    curl -s -L "https://github.com/devspace-cloud/devspace/releases/latest" | sed -nE 's!.*"([^"]*devspace-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o devspace && chmod +x devspace;

    sudo install devspace /usr/local/bin;
}

install_npm_deps () {
    sudo npm install -g \
        neovim \
        bash-language-server \
        dockerfile-language-server-nodejs \
        elasticdump \
        javascript-typescript-langserver \
        marked \
        prettier \
        pyright \
        standard \
    && echo -e '\033[1mNPM install success\033[0m'
}

install_python_deps() {
    pip3 install -U --user \
        "python-language-server[all]" \
        awscli \
        bandit \
        black \
        dataset \
        dateparser \
        django-stubs \
        docker-compose \
        flake8 \
        flake8-polyfill \
        ipdb \
        ipython \
        iredis \
        jedi \
        litecli \
        mypy \
        neovim \
        nptime \
        pgcli \
        pipenv \
        pydocstyle \
        pyflakes \
        pyinotify \
        python-dateutil \
        radon \
        requests \
        selenium \
        vim-vint \
        yamllint \
    && echo -e '\033[1mPIP install success\033[0m'
}



identify_os () {
    . /etc/os-release
    echo "$NAME" | tr '[:upper:]' '[:lower:]'
}


install_fish() {
    fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
    fish -c "fisher install jethrokuan/z"
}

change_default_shell() {
    sudo chsh $(whoami) -s $(which fish)
}

main () {
    OS_DETECTED=$(identify_os)

    if [ "$OS_DETECTED" == "ubuntu" ]; then
        echo "Ubuntu detected"
        install_base_debian
        install_go_packages

    elif [ "$OS_DETECTED" == "debian gnu/linux" ]; then
        echo "Ubuntu detected"
        install_base_debian

    elif [ "$OS_DETECTED" == "arch linux" ]; then
        echo "Arch detected"
        install_base_arch
        install_go_packages

    elif [ "$OS_DETECTED" == "manjaro linux" ]; then
        echo "Manjaro detected"
        install_base_manjaro
        install_go_packages

    elif [ "$OS_DETECTED" == "arch linux arm" ]; then
        echo "Arch detected"
        install_base_arch
    else
        echo "Didn't detect OS"
        exit 1
    fi

    install_npm_deps
    install_python_deps
    install_fish

    change_default_shell
}


main

