#!/usr/bin/env bash
# vim:foldmethod=marker:foldlevel=0

# Utils {{{

# TODO check if yay exists to avoid errors
identify_os () {
    . /etc/os-release
    echo $NAME | tr '[:upper:]' '[:lower:]'
}

setup_yay () {
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
}

docker() {
    sudo pacman -S docker
    sudo systemctl enable docker --now
    sudo gpasswd -a $USER docker
}

setup_services() {
    sudo systemctl enable bluetooth --now
    sudo systemctl enable dnsmasq --now

    docker
}

setup_user() {
    sudo gpasswd -a $USER rfkill
}

# NOTE: not used
virtd() {
    sudo pacman -S libvirt qemu ebtables virt-manager --needed --noconfirm
    sudo gpasswd -a $USER kvm
    sudo gpasswd -a $USER libvirt
    sudo systemctl enable libvirtd --now
}

setup_dconf() {
    dconf load  / < optional/dconf.conf
}
# }}}

# Arch {{{
install_yay_packages() {
    yay -S --needed --noconfirm consolas-font
    yay -S --needed --noconfirm dbeaver
    yay -S --needed --noconfirm insomnia
    yay -S --needed --noconfirm mailspring
    yay -S --needed --noconfirm google-chrome
    yay -S --needed --noconfirm authy
    yay -S --needed --noconfirm fondo
    yay -S --needed --noconfirm toptracker
    yay -S --needed --noconfirm ocs-url
    yay -S --needed --noconfirm ytmdesktop
    yay -S --needed --noconfirm megasync
}

install_base_desktop_arch () {
    # Check if yay is present and install it if not.
    command -v yay || setup_yay

    sudo pacman -S --needed --noconfirm docker
    sudo pacman -S --needed --noconfirm telegram-desktop
    sudo pacman -S --needed --noconfirm openvpn
    sudo pacman -S --needed --noconfirm playerctl  # Control player from keyboard
    sudo pacman -S --needed --noconfirm kitty  # GPU term
    sudo pacman -S --needed --noconfirm alacritty  # GPU term
    sudo pacman -S --needed --noconfirm xclip  # neovim shared copy/paste buffer

    # BT Sound and A2DP
    sudo pacman -S --needed --noconfirm blueman  # Because gnome-bluetooth suck balls
    sudo pacman -S --needed --noconfirm pulseaudio-bluetooth
    sudo pacman -S --needed --noconfirm pavucontrol
    sudo pacman -S --needed --noconfirm dnsmasq

    # Fonts
    # https://wiki.archlinux.org/index.php/Fonts
    sudo pacman -S --needed --noconfirm gnu-free-fonts
    sudo pacman -S --needed --noconfirm noto-fonts
    sudo pacman -S --needed --noconfirm noto-fonts-emoji
    sudo pacman -S --needed --noconfirm noto-fonts-extra
    sudo pacman -S --needed --noconfirm ttf-hack  # Terminal
    sudo pacman -S --needed --noconfirm ttf-liberation  # Mono fonts in browsers
    sudo pacman -S --needed --noconfirm ttf-roboto
    sudo pacman -S --needed --noconfirm ttf-roboto-mono

    # Icons
    sudo pacman -S --needed --noconfirm elementary-icon-theme

}
# }}}

# Debian {{{
install_desktop_debian () {
    sudo apt-get update
    sudo apt-get install -y openvpn
    sudo apt-get install -y docker.io
    sudo apt-get install -y xclip
    sudo apt-get install -y kitty
}
# }}}

# Gnome config {{{

install_gnome_extension() {
    extension_name=$1
    extension_id=$2

    gnome-extensions list | grep $extension_name > /dev/null  || \
        gnome-shell-extension-installer --yes $extension_id
    gnome-extensions enable $extension_name
}

configure_gnome () {
    sudo pacman -S --needed --noconfirm chrome-gnome-shell
    yay -S --needed --noconfirm gnome-shell-extension-installer

    gsettings set org.gnome.shell.app-switcher current-workspace-only true
    gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 7
    gsettings set org.gnome.desktop.peripherals.keyboard delay 200

    gnome-shell-extension-installer --update

    install_gnome_extension desktop-icons@xtilam 2452  # Desktop icons
    install_gnome_extension gsconnect@andyholmes.github.io 1319  # GSconnect
    install_gnome_extension unite@hardpixel.eu 1287  # Unite
    install_gnome_extension disableworkspaceanim@owilliams.mixxx.org 1328  # Workspace switch animation disabler
    install_gnome_extension disable-workspace-switcher-popup@github.com 959   # Workspace switch popup disabler
}
# }}}

configure_cinnamon() {
    gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 10
}

# Plamsa config {{{
configure_kde () {
    sudo pacman -S --needed --noconfirm gnome-keyring  # For mailspring to work
    sudo pacman -S --needed --noconfirm kvantum-qt5

    # Fix meta for opening menu
    kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.plasmashell,/PlasmaShell,org.kde.PlasmaShell,activateLauncherMenu"

    # Restart kwin
    qdbus org.kde.KWin /KWin reconfigure
}
# }}}


main () {
    setup_user
    install_base_desktop_arch
    install_yay_packages

    if [ "$XDG_SESSION_DESKTOP" == "gnome" ]; then
        echo "Detected Gnome"
        setup_dconf
        configure_gnome

    elif [ "$XDG_SESSION_DESKTOP" == "KDE" ]; then
        echo "Detected Plasma"
        configure_kde

    elif [ "$XDG_SESSION_DESKTOP" == "cinnamon" ]; then
        echo "Detected Cinnamon"
        setup_dconf
        configure_cinnamon

    else
        echo "Did not detect session. Check XDG_SESSION_DESKTOP variable. Current value is $XDG_SESSION_DESKTOP"

    fi

}

main
