#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive


# APT path
if hash pacman 2>/dev/null; then
    echo "Found pacman"
    PACKAGES_CONFIG=packages.pacman.yaml
    sudo pacman -S archlinux-keyring --needed
    sudo pacman -Syy
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    -c "${PACKAGES_CONFIG}" --plugin-dir "${BASEDIR}/dotbot-pacaur" "${@}"


# Pacman path
elif hash apt 2>/dev/null; then
    echo "Found apt"
    PACKAGES_CONFIG=packages.apt.yaml
    [[ `whoami` == "root" ]] \
        && apt update && apt install -y sudo python3-apt \
        || sudo apt update && sudo apt install -y python3-apt

    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    -c "${PACKAGES_CONFIG}" --plugin-dir "${BASEDIR}/dotbot_plugin_aptget" "${@}"

else
    echo "Warning! Didn't found packet manager, install dependencies manually."

fi


"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
-c "${CONFIG}" "${@}"
