#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive


# Debian based installation.
if hash pacman 2>/dev/null; then
    echo "Found pacman"
    PACKAGES_CONFIG=packages.pacman.yaml
    [[ `whoami` == "root" ]] && pacman -S sudo --noconfirm
    sudo pacman -S archlinux-keyring python3 --needed --noconfirm
    sudo pacman -Syy
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    -c "${PACKAGES_CONFIG}" --plugin-dir "${BASEDIR}/dotbot-pacaur" "${@}"


# Arch based installation.
elif hash apt-get 2>/dev/null; then
    echo "Found apt"
    PACKAGES_CONFIG=packages.apt.yaml
    [[ `whoami` == "root" ]] \
        && apt-get update && apt-get install -y sudo python3-apt \
        || sudo apt-get update && sudo apt-get install -y python3-apt

    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    -c "${PACKAGES_CONFIG}" --plugin-dir "${BASEDIR}/dotbot_plugin_aptget" "${@}"

else
    echo "Warning! Didn't found packet manager, install dependencies manually."

fi


"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
-c "${CONFIG}" "${@}"
