#!/bin/bash

install_base() {
    sudo emerge app-portage/layman
    sudo emerge \
        bat \
        make \
        git \
        stow \
        gnome-disk-utility \
        distcc \
        app-misc/jq \
        dev-python/pip \
        telegram-desktop \
        playerctl \
        x11-misc/xclip \
        fzf \
        app-emulation/docker \
        htop \
        pulseaudio \
        pavucontrol \
        rclone \
        python \
        mpv \
        neovim \
        nodejs

    sudo emerge \
        xfce-extra/xfce4-volumed-pulse \
        blueman

    sudo rc-update add bluetooth default

    sudo eselect repository add librewolf git https://gitlab.com/librewolf-community/browser/gentoo.git

}


install_npm_deps () {
    sudo npm install -g --quiet --silent @bitwarden/cli > /dev/null 2>&1
    sudo npm install -g --quiet --silent \
        neovim \
        bash-language-server \
        dockerfile-language-server-nodejs \
        javascript-typescript-langserver \
        prettier \
        pyright \
        standard > /dev/null 2>&1 \
    && echo -e "${BOLD}npm install success${NC}"
}

install_python_deps() {
    pip3 install -U --user setuptools wheel --no-warn-script-location

    pip3 install -U --user \
        "python-language-server[all]" \
        awscli \
        black \
        psycopg2 \
        smart-open \
        docker-compose \
        boto3 \
        dateparser \
        django-stubs \
        "django<3" \
        ipdb \
        ipython \
        saws \
        neovim \
        requests \
        selenium \
        youtube-dl \
        vim-vint \
        yamllint \
        --no-warn-script-location \
        && echo -e "${BOLD}pip install success${NC}"
}

install_neovim_plugins() {
    nvim test.py --headless +UpdateRemotePlugins +q > /dev/null 2>&1
    echo -e "${BOLD}neovim install success${NC}"
}

install_brave() {
    sudo layman -a brave-overlay    
    sudo layman -s brave-overlay
    sudo emerge www-client/brave-bin::brave-overlay
}

# install_base
install_npm_deps
install_python_deps
install_neovim_plugins
