#!/usr/bin/env bash
date=$(date +'%Y-%m-%d %I:%M %p')
inputlang=$(swaymsg -t get_inputs | jq '.[0].xkb_active_layout_name' -r)
battery=$(upower -d | grep percentage: | tail -1 | awk '{print $2}')

echo "BAT:$battery     $inputlang      $date"
