#!/usr/bin/env bash
source ~/.credentials/secure
set -ex

rclone sync ~/.aws b2:$B2_BUCKET_NAME/secure/.aws --create-empty-src-dirs
rclone sync ~/.credentials b2:$B2_BUCKET_NAME/secure/.credentials --create-empty-src-dirs
rclone sync ~/.gnupg b2:$B2_BUCKET_NAME/secure/.gnupg --create-empty-src-dirs
rclone sync ~/.kube b2:$B2_BUCKET_NAME/secure/.kube --create-empty-src-dirs
rclone sync ~/.ssh b2:$B2_BUCKET_NAME/secure/.ssh --create-empty-src-dirs
rclone sync ~/.config/mopidy b2:$B2_BUCKET_NAME/secure/.config/mopidy --create-empty-src-dirs
