#!/usr/bin/env bash
source ~/.config/credentials/secure || echo "Wasn't able to source config"

set -ex

rclone sync ~/.config/aws          b2:$B2_BUCKET_NAME/secure/.config/aws --create-empty-src-dirs
rclone sync ~/.config/credentials  b2:$B2_BUCKET_NAME/secure/.config/credentials --create-empty-src-dirs
rclone sync ~/.config/TopTracker   b2:$B2_BUCKET_NAME/secure/.config/TopTracker --create-empty-src-dirs
rclone sync ~/.config/gnupg        b2:$B2_BUCKET_NAME/secure/.config/gnupg --create-empty-src-dirs
rclone sync ~/.config/kube         b2:$B2_BUCKET_NAME/secure/.config/kube --create-empty-src-dirs

rclone sync ~/.ssh                 b2:$B2_BUCKET_NAME/secure/.ssh --create-empty-src-dirs
