#!/usr/bin/env bash
set -ex

rclone sync ~/.config/gnupg        b2:$B2_BUCKET_NAME/secure/.config/gnupg --create-empty-src-dirs
rclone sync ~/.config/kube         b2:$B2_BUCKET_NAME/secure/.config/kube --create-empty-src-dirs
rclone sync ~/.ssh                 b2:$B2_BUCKET_NAME/secure/.ssh --create-empty-src-dirs

mkdir -p ~/Documents/secure
cp -r ~/.config/gnupg        ~/Documents/secure/gnupg
cp -r ~/.config/kube         ~/Documents/secure/kube
cp -r ~/.ssh                 ~/Documents/secure/ssh
