#!/usr/bin/env bash

set -ex

wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list

sudo apt-get update && sudo apt-get install -y mopidy mopidy-spotify mopidy-mpd mopidy-mpris

sudo systemctl disable mopidy

# Web frontend
sudo python3 -m pip install Mopidy-Iris

# Pick up where you left off
# mkdir -p ~/.local/share/mopidy/autoplay/
# sudo python3 -m pip install Mopidy-Autoplay

# CLI interface (TODO find vim-like alternative)
# sudo apt-get -y install ncmpcpp
