#!/usr/bin/env bash
set -ex

sudo add-apt-repository -y ppa:lutris-team/lutris

wget -nc https://dl.winehq.org/wine-builds/winehq.key; sudo apt-key add winehq.key; rm winehq.key

. /etc/os-release && sudo add-apt-repository -y "deb https://dl.winehq.org/wine-builds/ubuntu/ $UBUNTU_CODENAME main"

sudo apt-get install -y lutris
sudo apt-get install -y --install-recommends winehq-staging
sudo apt-get install -y libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 libsqlite3-0:i386

# Temporary fix for missing DXVK
# [ ! -f "$HOME/.local/share/lutris/runtime/dxvk/dxvk_versions.json" ] && wget https://cdn.discordapp.com/attachments/538903130704838656/796102070825779250/dxvk_versions.json -P $HOME/.local/share/lutris/runtime/dxvk
