#!/usr/bin/env bash

bspwm() {
    sudo pacman -S --needed --noconfirm  \
        bspwm \
        dmenu \
        nitrogen \
        picom \
        polybar \
        sxhkd \
    && echo -e '\033[1mBase install success\033[0m'
}

bspwm
