#!/usr/bin/env bash

bspwm() {
    sudo pacman -S --needed --noconfirm sxhkd
    sudo pacman -S --needed --noconfirm bspwm
    sudo pacman -S --needed --noconfirm dmenu
    sudo pacman -S --needed --noconfirm nautilus
    sudo pacman -S --needed --noconfirm nitrogen
    sudo pacman -S --needed --noconfirm picom

    yay -S --needed --noconfirm polybar
}

bspwm
