#!/usr/bin/env bash

sudo apt-get update


sudo apt-get install -y \
    git \
    stow \
    zsh-syntax-highlighting \
    pipx \
    make \
    docker.io \
    avahi-daemon \
    zsh \
    build-essential \
    tmux \
    poetry \
    neovim

pipx install poetry

sudo gpasswd -a $USER docker

sudo chsh $USER -s $(which zsh)

curl -sS https://starship.rs/install.sh | sh


nvim --headless "+Lazy! sync" +qa
nvim --headless "+MasonInstallAll" +qa

# git clone https://github.com/nzagorsky/dotfiles
# cd dotfiles
# ./install.sh
