#!/usr/bin/env bash
set -ex

mkdir -p ~/.config/credentials/
mkdir -p ~/.config/mopidy/

# Setup ~/.credentials/secure to access B2.
bw login || echo "Logged in already"
bw list items --search 'credentials.secure' | jq --raw-output ".[0].notes" > ~/.config/credentials/secure && source ~/.config/credentials/secure

# Add rclone b2 config
rclone config delete b2; rclone config create b2 b2
rclone ls b2: > /dev/null 2>&1 || echo "NOTE: Failed to setup configuration"

# Setup rest of the credentials
rclone sync b2:$B2_BUCKET_NAME/secure/.config/aws           ~/.config/aws --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.config/credentials   ~/.config/credentials --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.config/mopidy        ~/.config/mopidy --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.config/TopTracker    ~/.config/TopTracker --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.config/gnupg         ~/.config/gnupg --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.config/kube          ~/.config/kube --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.ssh                  ~/.ssh --create-empty-src-dirs

chmod -R 700 ~/.config/aws
chmod -R 700 ~/.config/credentials
chmod -R 700 ~/.config/mopidy
chmod -R 700 ~/.config/TopTracker
chmod -R 700 ~/.config/gnupg
chmod -R 700 ~/.config/kube
chmod -R 700 ~/.ssh
