#!/usr/bin/env bash
set -ex

set -ex

# Setup ~/.credentials/secure to access B2.
mkdir -p ~/.credentials/
bw login || echo
bw list items --search 'credentials.secure' | jq --raw-output ".[0].notes" > ~/.credentials/secure && source ~/.credentials/secure

# Add rclone b2 config
rclone config delete b2; rclone config create b2 b2
rclone ls b2: 2> /dev/null 2>&1 || echo "NOTE: Failed to setup configuration"
[ ! -d "/mnt/b2" ] && sudo mkdir -p /mnt/b2 && sudo chown $USER:$USER /mnt/b2

# Setup rest of the credentials
rclone sync b2:$B2_BUCKET_NAME/secure/.aws ~/.aws --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.credentials ~/.credentials --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.gnupg ~/.gnupg --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.kube ~/.kube --create-empty-src-dirs
rclone sync b2:$B2_BUCKET_NAME/secure/.ssh ~/.ssh --create-empty-src-dirs

chmod 700 -R ~/.aws
chmod 700 -R ~/.credentials
chmod 700 -R ~/.gnupg
chmod 700 -R ~/.kube
chmod 700 -R ~/.ssh
