#!/usr/bin/env bash

set -ex

install_neovim_plugins() {
	nvim --headless "+Lazy! sync" +qa
}

install_brew_packages() {
	brew tap homebrew/cask-fonts

	brew install --quiet --cask font-hack-nerd-font
	brew install --quiet --cask another-redis-desktop-manager --no-quarantine

	brew install --quiet \
		autoconf \
		automake \
		bat \
		curl \
		docker-credential-helper \
		eza \
		fd \
		fish \
		fzy \
		git-lfs \
		go \
		hammerspoon \
		helm \
		htop \
		iina \
		jq \
		kubectl \
		libxmlsec1 \
		llvm \
		mosh \
		mysql \
		ncdu \
		neovim \
		node \
		openvpn \
		postgresql \
		pyenv \
		rclone \
		rectangle \
		ripgrep \
		rustup-init \
		shfmt \
		sqlite3 \
		swiftformat \
		universal-ctags \
		watch \
		wezterm \
		wget \
		wireguard-tools \
		youtube-dl \
		yq \
		zellij
}

install_brew_packages
install_neovim_plugins
