#! /bin/sh
# Init {{{
# Setup Xresources
xrdb -merge ~/.Xresources

# Speed up keyboard
xset r rate 190 50

sxhkd &
picom -b &
sxhkd &
kupfer --no-splash &
pkill polybar; polybar mybar -r &
nitrogen --restore &
# }}}
# BSPWM config {{{

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# }}}
# vim:foldmethod=marker:foldlevel=0
