#!/usr/bin/bash

# Status line settings
set -g status "on"
set -g status-style "bg=default,fg=colour137,dim"
set -g status-justify "left"
set -g status-position "bottom"

# Left status line part
set -g status-left " "
set -g status-left-style "bg=default"
set -g status-left-length 100

# Right status line part
set -g status-right "#{prefix_highlight} #[fg=colour0,nobold,nounderscore,noitalics] #[fg=colour243] %d/%m/%Y %R"

set -g status-right-style "none"
set -g status-right-length "160"

# Message settings
set -g message-style "bg=colour0,fg=colour2"

# Border settings
set -g pane-border-style "bg=default,fg=colour240"
set -g pane-active-border-style "bg=default,fg=colour245"

# Current (active) window setting
setw -g window-status-current-format "#W"
setw -g window-status-current-style "bg=default,fg=blue,bold"
setw -g window-status-style "bg=default,fg=colour240"
setw -g window-status-format "#W"
setw -g window-status-separator " "

# Activity setting
setw -g window-status-activity-style "fg=yellow, none"

