#!/usr/bin/bash

# Status line settings
set -g status "on"
set -g status-attr dim
set -g status-bg default
set -g status-fg colour137
set -g status-justify "left"
set -g status-position "bottom"

# Left status line part
# set -g status-left "#[fg=colour243] #S #[fg=colour2,nobold,nounderscore,noitalics]"
set -g status-left ""
set -g status-left-attr "none"
set -g status-left-length "100"

# Right status line part
set -g status-right "#{prefix_highlight} #[fg=colour0,nobold,nounderscore,noitalics] #[fg=colour243] %d/%m/%Y %R"
set -g status-right-attr "none"
set -g status-right-length "160"

# Message settings
set -g message-fg "colour2"
set -g message-bg "colour0"

# Border settings
set -g pane-border-bg default
set -g pane-border-fg "colour240"

set -g pane-active-border-bg default
set -g pane-active-border-fg "colour245"

# Current (active) window setting
setw -g window-status-current-fg colour1
setw -g window-status-current-bg colour119
setw -g window-status-current-format "#[fg=colour0,nobold,nounderscore,noitalics] #[fg=colour1]#W #[fg=colour0,nobold,nounderscore,noitalics]"

# Inactive window setting
setw -g window-status-bg "default"
setw -g window-status-fg "colour243"
setw -g window-status-attr "none"
setw -g window-status-separator ""
setw -g window-status-format "#[fg=colour0,nobold,nounderscore,noitalics] #[default]#W #[fg=colour0,nobold,nounderscore,noitalics]"

# Activity setting
setw -g window-status-activity-attr "none"
setw -g window-status-activity-fg "colour2"

