#!/usr/bin/env bash

MENU_MODE=$1  # [drun, run]

# If no arg is passed then it's run.
if [ -z $MENU_MODE ]
  then
    MENU_MODE="run"
fi

# Colors
BACKGROUND="212121"
FOREGROUND="bdbdbd"

# Visibility variables. NOTE: Alpha: From 00 to FF
VISIBLE="CC"
TRANSPARENT="00"

# Define combinations.
ACTIVETEXTCOLOR=$BACKGROUND
TEXTCOLOR=$FOREGROUND
ACTIVEROW=$VISIBLE$FOREGROUND
USELESS="$TRANSPARENT$FOREGROUND"


rofi \
    -modi "run,drun" \
    -show $MENU_MODE \
    -color-normal "#$TRANSPARENT$BACKGROUND, #$TEXTCOLOR, #$USELESS, #$ACTIVEROW, #$ACTIVETEXTCOLOR" \
    -color-window "#$VISIBLE$BACKGROUND, #$BACKGROUND, #$BACKGROUND" \
    -matching fuzzy \
    -lines 7 \
    -width 800 \
    -padding 100 \
    -no-show-match \   # Disable underlining
    -font "Ubuntu 12" \
    -bw 0 \  
